#net architecture
architecture: densenet100bc

#log and checkpoint
data_path: ./data
ckpt_path: ./
ckpt_name: densenet100bc

#datasets
num_classes: 10
dataset: cifar10

#training parameters
use_gpu: True
input_size: 32
epochs: 300
batch_size: 64
test_batch: 200
eval_freq: 2
workers: 4

#optimize
optimize:
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True

#regularizatoin
mixup: False
mixup_alpha: 0.4

augmentation:
  normalize: True
  random_crop: True
  random_horizontal_flip: True
  cutout: False
  holes: 1
  length: 8

#learning rate scheduler
lr_scheduler:
  type: STEP
  base_lr: 0.1
  lr_epochs: [150,225]
  lr_mults: 0.1
  min_lr: 0.0
  lower_bound: -6.0
  upper_bound: 3.0
