# net architecture
architecture: preresnet20

# log and checkpoint
data_path: ./data
ckpt_path: ./
ckpt_name: preresnet20

# datasets
num_classes: 10
dataset: cifar10

# training parameters
use_gpu: True
input_size: 32
epochs: 250
batch_size: 128
test_batch: 200
eval_freq: 2
workers: 4

# optimizer
optimize:
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True

# regularization
mixup: False
mixup_alpha: 0.4

augmentation:
  normalize: True
  random_crop: True
  random_horizontal_flip: True
  cutout: False
  holes: 1
  length: 8

# learning rate scheduler
lr_scheduler:
  #type: SETP or COSINE or HTD
  type: STEP
  base_lr: 0.1
  #only for STEP
  lr_epochs: [100, 150, 200]
  lr_mults: 0.1
  #for HTD and COSINE
  min_lr: 0.0
  #only for HTD
  lower_bound: -6.0
  upper_bound: 3.0